version: "3.8"

networks:
  eazy-backend-interview:
    name: "eazy-backend-interview"
    driver: bridge

volumes:
  eazy-backend-interview:

services:
  eazy-backend-interview-database:
    container_name: eazy-backend-interview-database
    image: postgres:14.5
    volumes:
      - eazy-backend-interview:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: eazy-backend-interview-database
      POSTGRES_PORT: 5432
      POSTGRES_DB: eazy-backend-interview
      POSTGRES_USER: eazy
      POSTGRES_PASSWORD: eazy
    ports:
      - 5432:5432
    networks:
      - eazy-backend-interview

  eazy-backend-interview:
    container_name: eazy-backend-interview
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    restart: on-failure
    networks:
      - eazy-backend-interview
    ports:
      - 8000:8000
    depends_on:
      - eazy-backend-interview-database
  