name: Mirrow repository to BitBucket

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  mirror:
    name: Mirror repository to BitBucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          password: ${{ secrets.BITBUCKET_APP_PASSWORD }}
          spacename: eazy-insure
          repository: nestjs-service-template
          username: bogdanbucur-eazy